=== Thinkfreer/mybatis-tool/metadata/jaxb/DAOTool.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="filePath" type="xsd:string"></xsd:element>
    <xsd:element name="project" type="xsd:string"></xsd:element>
    <xsd:element name="name" type="xsd:string"></xsd:element>
    <xsd:element name="dbname" type="xsd:string"></xsd:element>
    <xsd:element name="dbtype" type="xsd:string"></xsd:element>
    <xsd:element name="id" type="xsd:string"></xsd:element>
    <xsd:element name="sql" type="xsd:string"></xsd:element>
    <xsd:element name="type" type="xsd:string"></xsd:element>
    <xsd:element name="table" type="xsd:string"></xsd:element>
    <xsd:element name="null" type="xsd:boolean"></xsd:element>
    <xsd:element name="unique" type="xsd:boolean"></xsd:element>
    <xsd:element name="default" type="xsd:string"></xsd:element>

    <xsd:element name="daoTool" type="daoToolType"></xsd:element>
    <xsd:element name="modules" type="modulesType"></xsd:element>
    <xsd:element name="module" type="moduleType"></xsd:element>
    <xsd:element name="model" type="modelType"></xsd:element>
    <xsd:element name="prop" type="propType"></xsd:element>
    <xsd:element name="finder" type="finderType"></xsd:element>

	<!--
    <xsd:simpleType name="typeSType" >
        <xsd:restriction base="xsd:string" >
            <xsd:enumeration value="Boolean" />
            <xsd:enumeration value="String" />
            <xsd:enumeration value="Integer" />
            <xsd:enumeration value="Long" />
            <xsd:enumeration value="Float" />
            <xsd:enumeration value="Double" />
            <xsd:enumeration value="Timestamp" />
            <xsd:enumeration value="Date" />
        </xsd:restriction>
    </xsd:simpleType>
    -->


    <xsd:complexType name="daoToolType">
        <xsd:sequence>
            <xsd:element ref="filePath" maxOccurs="1" />
            <xsd:element ref="dbname" maxOccurs="1" />
            <xsd:element ref="dbtype" maxOccurs="1" />
            <xsd:element ref="project" maxOccurs="1" />
            <xsd:element ref="modules" maxOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="modulesType">
        <xsd:sequence>
            <xsd:element ref="module" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="moduleType">
        <xsd:sequence>
            <xsd:element ref="name" maxOccurs="1"/>
            <xsd:element ref="model" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="modelType">
        <xsd:sequence>
            <xsd:element ref="name" maxOccurs="1" />
            <xsd:element ref="table" maxOccurs="1" />
            <xsd:element ref="prop" maxOccurs="unbounded" />
            <xsd:element ref="finder" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="propType">
        <xsd:sequence>
            <xsd:element ref="name" maxOccurs="1" />
            <xsd:element ref="type" maxOccurs="1" />
            <xsd:element ref="null" maxOccurs="1"/>
            <xsd:element ref="unique" maxOccurs="1"/>
            <xsd:element ref="default" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="finderType">
        <xsd:sequence>
            <xsd:element ref="id" maxOccurs="1"/>
            <xsd:element ref="sql" maxOccurs="1" />
        </xsd:sequence>
    </xsd:complexType>
    
</xsd:schema>

=== Thinkfreer/mybatis-tool/metadata/sample/ilink-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<daoTool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./metadata/jaxb/DAOTool.xsd">

	<filePath>metadata/gen</filePath>
	<project>com.ilink.server</project>
	<modules>
		<module>
			<name>account</name>
			<model>
				<name>accountXmpp</name>
				<table>t_account_xmpp</table>
				<prop><name>password2</name><type>String</type></prop>
				<prop><name>username</name><type>String</type></prop>
				<prop><name>type</name><type>String</type></prop>
				<prop><name>domain</name><type>String</type></prop>
				<prop><name>resource</name><type>String</type></prop>
			</model>
			<model>
				<name>accountTwitter</name>
				<table>t_account_twitter</table>
				<prop><name>password2</name><type>String</type></prop>
				<prop><name>username</name><type>String</type></prop>
				<prop><name>type</name><type>String</type></prop>
				<prop><name>domain</name><type>String</type></prop>
				<prop><name>oauth_token</name><type>String</type><null>true</null></prop>
				<prop><name>oauth_secret</name><type>String</type><null>true</null></prop>
				<prop><name>uid</name><type>Integer</type></prop>
			</model>
			<model>
				<name>accountBindingXTwitter</name>
				<table>t_account_binding_xt</table>
				<prop><name>account_xmpp_id</name><type>Integer</type></prop>
				<prop><name>account_twitter_id</name><type>Integer</type></prop>
			</model>
		</module>
		<module>
			<name>app</name>
			<model>
				<name>app</name>
				<table>t_app</table>
				<prop><name>name</name><type>String</type></prop>
				<prop><name>namecn</name><type>String</type><null>true</null></prop>
				<prop><name>type</name><type>String</type></prop>
				<prop><name>logo</name><type>String</type><null>true</null></prop>
				<prop><name>available</name><type>Integer</type></prop>
			</model>
		</module>
		<module>
			<name>job</name>
			<model>
				<name>jobTSinaTweetStat</name>
				<table>t_job_tsina_tweet_stat</table>
				<prop><name>tids</name><type>String</type></prop>
				<prop><name>status</name><type>Integer</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
			</model>
		</module>
		<module>
			<name>twitterSina</name>
			<model>
				<name>twitterSinaUser</name>
				<table>t_twitter_sina_user</table>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>name</name><type>String</type></prop>
				<prop><name>location</name><type>String</type><null>true</null></prop>
				<prop><name>url</name><type>String</type><null>true</null></prop>
				<prop><name>city</name><type>Integer</type><null>true</null></prop>
				<prop><name>description</name><type>String</type><null>true</null></prop>
				<prop><name>tweet_count</name><type>Integer</type><null>true</null></prop>
				<prop><name>follow_count</name><type>Integer</type><null>true</null></prop>
				<prop><name>fans_count</name><type>Integer</type><null>true</null></prop>
				<prop><name>favourite_count</name><type>Integer</type><null>true</null></prop>
				<prop><name>province</name><type>Integer</type><null>true</null></prop>
				<prop><name>domain</name><type>String</type><null>true</null></prop>
				<prop><name>create_date</name><type>Date</type></prop>
				<prop><name>gender</name><type>String</type><null>true</null></prop>
				<prop><name>profile_image_url</name><type>String</type><null>true</null></prop>
				<prop><name>verified</name><type>Integer</type><null>true</null></prop>
				<prop><name>screen_name</name><type>String</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
			</model>
			<model>
				<name>twitterSinaTweet</name>
				<table>t_twitter_sina_tweet</table>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>content</name><type>String</type></prop>
				<prop><name>bmiddle_pic</name><type>String</type><null>true</null></prop>
				<prop><name>thumbnail_pic</name><type>String</type><null>true</null></prop>
				<prop><name>original_pic</name><type>String</type><null>true</null></prop>
				<prop><name>source</name><type>String</type><null>true</null></prop>
				<prop><name>create_date</name><type>Date</type></prop>
				<prop><name>retid</name><type>Long</type></prop>
			</model>
			<model>
				<name>twitterSinaInbox</name>
				<table>t_twitter_sina_inbox</table>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>create_date</name><type>Date</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
			</model>
			<model>
				<name>twitterSinaTweetStat</name>
				<table>t_twitter_sina_tweet_stat</table>
				<prop><name>favourite_count</name><type>Long</type><null>true</null></prop>
				<prop><name>repost_count</name><type>Long</type><null>true</null></prop>
				<prop><name>comment_count</name><type>Long</type><null>true</null></prop>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
			</model>
			<model>
				<name>twitterSinaDailyRank</name>
				<table>t_twitter_sina_daily_rank</table>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
				<prop><name>rank</name><type>Float</type><null>true</null></prop>
				<prop><name>date_tag</name><type>Integer</type></prop>
			</model>
			<model>
				<name>twitterSinaDailySend</name>
				<table>t_twitter_sina_daily_send</table>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
				<prop><name>date_tag</name><type>Integer</type></prop>
			</model>
			<model>
				<name>twitterSinaDailyHistory</name>
				<table>t_twitter_sina_daily_history</table>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
				<prop><name>rank</name><type>Float</type><null>true</null></prop>
				<prop><name>date_tag</name><type>Integer</type></prop>
			</model>
			<model>
				<name>twitterSinaDailyBlack</name>
				<table>t_twitter_sina_daily_black</table>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
				<prop><name>date_tag</name><type>Integer</type></prop>
			</model>
			<model>
				<name>twitterSinaUserRelate</name>
				<table>t_twitter_sina_user_relate</table>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>fansid</name><type>Integer</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
			</model>
			<model>
				<name>twitterSinaFavorite</name>
				<table>t_twitter_sina_favorite</table>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>ownerid</name><type>Integer</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
			</model>
			<model>
				<name>twitterSinaComment</name>
				<table>t_twitter_sina_comment</table>
				<prop><name>cid</name><type>Long</type></prop>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>ownerid</name><type>Integer</type></prop>
				<prop><name>comment</name><type>String</type></prop>
				<prop><name>create_date</name><type>Date</type></prop>
				<prop><name>source</name><type>String</type><null>true</null></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
			</model>
			<model>
				<name>twitterSinaPmsg</name>
				<table>t_twitter_sina_pmsg</table>
				<prop><name>mid</name><type>Integer</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>receiverid</name><type>Integer</type></prop>
				<prop><name>msg</name><type>String</type></prop>
				<prop><name>create_date</name><type>Date</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
			</model>
			
			<model>
				<name>twitterSinaRepost</name>
				<table>t_twitter_sina_repost</table>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>retid</name><type>Long</type></prop>
				<prop><name>ownerid</name><type>Integer</type></prop>
				<prop><name>create_date</name><type>Date</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
			</model>
			<model>
				<name>twitterSinaAt</name>
				<table>t_twitter_sina_at</table>
				<prop><name>tid</name><type>Long</type></prop>
				<prop><name>ownerid</name><type>Integer</type></prop>
				<prop><name>uid</name><type>Integer</type></prop>
				<prop><name>name</name><type>String</type></prop>
				<prop><name>create_date</name><type>Date</type></prop>
				<prop><name>version</name><type>Timestamp</type></prop>
			</model>
			<model>
				<name>twitterSinaConfig</name>
				<table>t_twitter_sina_config</table>
				<prop><name>name</name><type>String</type></prop>
				<prop><name>description</name><type>String</type><null>true</null></prop>
				<prop><name>value</name><type>String</type></prop>
			</model>
		</module>
	</modules>
</daoTool>

=== Thinkfreer/mybatis-tool/daoTool-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<daoTool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./metadata/jaxb/DAOTool.xsd">

	<filePath>metadata/comp</filePath>
	<project>org.conan.dm</project>
	<dbname>competition</dbname>
	<dbtype>mysql</dbtype>
	
	<modules>
        <module>
            <name>quiz</name>
            <model>
                <name>quiz</name>
                <table>t_quiz</table>
                <prop><name>title</name><type>varchar(16)</type></prop>
                <prop><name>content</name><type>mediumtext</type><null>true</null></prop>
                <prop><name>create_date</name><type>timestamp</type><default>now()</default><null>true</null></prop>
                <prop><name>end_date</name><type>timestamp</type><null>true</null></prop>
                <prop><name>uid</name><type>int</type></prop>
            </model>
            <model>
                <name>quizData</name>
                <table>t_quiz_data</table>
                <prop><name>qid</name><type>int</type></prop>
                <prop><name>type</name><type>int</type></prop>
                <prop><name>file</name><type>varchar(512)</type></prop>
                <prop><name>local</name><type>varchar(512)</type></prop>
                <prop><name>create_date</name><type>timestamp</type><default>now()</default><null>true</null></prop>
            </model>
            <model>
                <name>quizSubmit</name>
                <table>t_quiz_submit</table>
                <prop><name>qid</name><type>int</type></prop>
                <prop><name>lang</name><type>varchar(16)</type><default>R</default><null>true</null></prop>
                <prop><name>code</name><type>mediumtext</type></prop>
                <prop><name>create_date</name><type>timestamp</type><default>now()</default><null>true</null></prop>
                <prop><name>uid</name><type>int</type></prop>
                <prop><name>status</name><type>int</type><default>0</default><null>true</null></prop>
                <prop><name>result</name><type>int</type><default>0</default><null>true</null></prop>
            </model>
        </module>
	</modules>
</daoTool>

=== Thinkfreer/mybatis-tool/daoTool-config-aocheng.xml
<?xml version="1.0" encoding="UTF-8"?>
<daoTool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./metadata/jaxb/DAOTool.xsd">

	<filePath>metadata/gen</filePath>
	<project>org.conan.aocheng</project>
	<modules>
		<module>
			<name>ac</name>
			<model>
				<name>catalog</name>
				<table>t_ac_catalog</table>
				<prop><name>name</name><type>String</type></prop>
			</model>
			<model>
				<name>prod</name>
				<table>t_ac_prod</table>
				<prop><name>catid</name><type>Integer</type></prop>
				<prop><name>title</name><type>String</type></prop>
				<prop><name>content</name><type>String</type><null>true</null></prop>
				<prop><name>image_url</name><type>String</type><null>true</null></prop>
				<prop><name>description</name><type>String</type><null>true</null></prop>
				<prop><name>create_date</name><type>Timestamp</type></prop>
			</model>
		</module>
	</modules>
</daoTool>

=== Thinkfreer/mybatis-tool/daoTool-config-ad.xml
<?xml version="1.0" encoding="UTF-8"?>
<daoTool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./metadata/jaxb/DAOTool.xsd">

	<filePath>metadata/gen</filePath>
	<project>org.conan.taobao</project>
	<modules>
		<module>
			<name>ad</name>
			<model>
				<name>user</name>
				<table>t_ad_user</table>
				<prop><name>userid</name><type>Long</type></prop>
				<prop><name>nick</name><type>String</type></prop>
				<prop><name>uid</name><type>String</type></prop>
				<prop><name>create_date</name><type>Date</type></prop>
			</model>
			<model>
				<name>config</name>
				<table>t_ad_config</table>
				<prop><name>nick</name><type>String</type></prop>
				<prop><name>width</name><type>Integer</type></prop>
				<prop><name>pic_size</name><type>Integer</type></prop>
				<prop><name>enter_show</name><type>Integer</type></prop>
				<prop><name>favor_show</name><type>Integer</type></prop>
				<prop><name>title_show</name><type>Integer</type></prop>
				<prop><name>shoptype</name><type>Integer</type></prop>
				<prop><name>create_date</name><type>Timestamp</type></prop>
			</model>
			<model>
				<name>item</name>
				<table>t_ad_item</table>
				<prop><name>itemid</name><type>Long</type></prop>
				<prop><name>nick</name><type>String</type></prop>
				<prop><name>title</name><type>String</type></prop>
				<prop><name>price</name><type>Float</type></prop>
				<prop><name>pic_url</name><type>String</type></prop>
				<prop><name>desc_url</name><type>String</type></prop>
				<prop><name>dtime</name><type>Date</type></prop>
				<prop><name>create_date</name><type>Timestamp</type></prop>
			</model>
		</module>
	</modules>
</daoTool>
